# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bober/Moving-Picture-Studio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bober/Moving-Picture-Studio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bober/Moving-Picture-Studio/CMakeFiles /home/bober/Moving-Picture-Studio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bober/Moving-Picture-Studio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MPS

# Build rule for target.
MPS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MPS
.PHONY : MPS

# fast build rule for target.
MPS/fast:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/build
.PHONY : MPS/fast

src/app.o: src/app.cpp.o

.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i

.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s

.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/app_run.o: src/app_run.cpp.o

.PHONY : src/app_run.o

# target to build an object file
src/app_run.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/app_run.cpp.o
.PHONY : src/app_run.cpp.o

src/app_run.i: src/app_run.cpp.i

.PHONY : src/app_run.i

# target to preprocess a source file
src/app_run.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/app_run.cpp.i
.PHONY : src/app_run.cpp.i

src/app_run.s: src/app_run.cpp.s

.PHONY : src/app_run.s

# target to generate assembly for a file
src/app_run.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/app_run.cpp.s
.PHONY : src/app_run.cpp.s

src/error.o: src/error.cpp.o

.PHONY : src/error.o

# target to build an object file
src/error.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/error.cpp.o
.PHONY : src/error.cpp.o

src/error.i: src/error.cpp.i

.PHONY : src/error.i

# target to preprocess a source file
src/error.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/error.cpp.i
.PHONY : src/error.cpp.i

src/error.s: src/error.cpp.s

.PHONY : src/error.s

# target to generate assembly for a file
src/error.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/error.cpp.s
.PHONY : src/error.cpp.s

src/framebuffermanager.o: src/framebuffermanager.cpp.o

.PHONY : src/framebuffermanager.o

# target to build an object file
src/framebuffermanager.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/framebuffermanager.cpp.o
.PHONY : src/framebuffermanager.cpp.o

src/framebuffermanager.i: src/framebuffermanager.cpp.i

.PHONY : src/framebuffermanager.i

# target to preprocess a source file
src/framebuffermanager.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/framebuffermanager.cpp.i
.PHONY : src/framebuffermanager.cpp.i

src/framebuffermanager.s: src/framebuffermanager.cpp.s

.PHONY : src/framebuffermanager.s

# target to generate assembly for a file
src/framebuffermanager.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/framebuffermanager.cpp.s
.PHONY : src/framebuffermanager.cpp.s

src/lib/SDL2_rotozoom.o: src/lib/SDL2_rotozoom.cpp.o

.PHONY : src/lib/SDL2_rotozoom.o

# target to build an object file
src/lib/SDL2_rotozoom.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/lib/SDL2_rotozoom.cpp.o
.PHONY : src/lib/SDL2_rotozoom.cpp.o

src/lib/SDL2_rotozoom.i: src/lib/SDL2_rotozoom.cpp.i

.PHONY : src/lib/SDL2_rotozoom.i

# target to preprocess a source file
src/lib/SDL2_rotozoom.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/lib/SDL2_rotozoom.cpp.i
.PHONY : src/lib/SDL2_rotozoom.cpp.i

src/lib/SDL2_rotozoom.s: src/lib/SDL2_rotozoom.cpp.s

.PHONY : src/lib/SDL2_rotozoom.s

# target to generate assembly for a file
src/lib/SDL2_rotozoom.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/lib/SDL2_rotozoom.cpp.s
.PHONY : src/lib/SDL2_rotozoom.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/modules/module.o: src/modules/module.cpp.o

.PHONY : src/modules/module.o

# target to build an object file
src/modules/module.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/modules/module.cpp.o
.PHONY : src/modules/module.cpp.o

src/modules/module.i: src/modules/module.cpp.i

.PHONY : src/modules/module.i

# target to preprocess a source file
src/modules/module.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/modules/module.cpp.i
.PHONY : src/modules/module.cpp.i

src/modules/module.s: src/modules/module.cpp.s

.PHONY : src/modules/module.s

# target to generate assembly for a file
src/modules/module.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/modules/module.cpp.s
.PHONY : src/modules/module.cpp.s

src/musicload.o: src/musicload.cpp.o

.PHONY : src/musicload.o

# target to build an object file
src/musicload.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/musicload.cpp.o
.PHONY : src/musicload.cpp.o

src/musicload.i: src/musicload.cpp.i

.PHONY : src/musicload.i

# target to preprocess a source file
src/musicload.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/musicload.cpp.i
.PHONY : src/musicload.cpp.i

src/musicload.s: src/musicload.cpp.s

.PHONY : src/musicload.s

# target to generate assembly for a file
src/musicload.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/musicload.cpp.s
.PHONY : src/musicload.cpp.s

src/pixel.o: src/pixel.cpp.o

.PHONY : src/pixel.o

# target to build an object file
src/pixel.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/pixel.cpp.o
.PHONY : src/pixel.cpp.o

src/pixel.i: src/pixel.cpp.i

.PHONY : src/pixel.i

# target to preprocess a source file
src/pixel.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/pixel.cpp.i
.PHONY : src/pixel.cpp.i

src/pixel.s: src/pixel.cpp.s

.PHONY : src/pixel.s

# target to generate assembly for a file
src/pixel.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/pixel.cpp.s
.PHONY : src/pixel.cpp.s

src/render/buffer.o: src/render/buffer.cpp.o

.PHONY : src/render/buffer.o

# target to build an object file
src/render/buffer.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/render/buffer.cpp.o
.PHONY : src/render/buffer.cpp.o

src/render/buffer.i: src/render/buffer.cpp.i

.PHONY : src/render/buffer.i

# target to preprocess a source file
src/render/buffer.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/render/buffer.cpp.i
.PHONY : src/render/buffer.cpp.i

src/render/buffer.s: src/render/buffer.cpp.s

.PHONY : src/render/buffer.s

# target to generate assembly for a file
src/render/buffer.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/render/buffer.cpp.s
.PHONY : src/render/buffer.cpp.s

src/render/func.o: src/render/func.cpp.o

.PHONY : src/render/func.o

# target to build an object file
src/render/func.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/render/func.cpp.o
.PHONY : src/render/func.cpp.o

src/render/func.i: src/render/func.cpp.i

.PHONY : src/render/func.i

# target to preprocess a source file
src/render/func.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/render/func.cpp.i
.PHONY : src/render/func.cpp.i

src/render/func.s: src/render/func.cpp.s

.PHONY : src/render/func.s

# target to generate assembly for a file
src/render/func.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/render/func.cpp.s
.PHONY : src/render/func.cpp.s

src/scenes/editor/colorselector/colorselector.o: src/scenes/editor/colorselector/colorselector.cpp.o

.PHONY : src/scenes/editor/colorselector/colorselector.o

# target to build an object file
src/scenes/editor/colorselector/colorselector.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/colorselector/colorselector.cpp.o
.PHONY : src/scenes/editor/colorselector/colorselector.cpp.o

src/scenes/editor/colorselector/colorselector.i: src/scenes/editor/colorselector/colorselector.cpp.i

.PHONY : src/scenes/editor/colorselector/colorselector.i

# target to preprocess a source file
src/scenes/editor/colorselector/colorselector.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/colorselector/colorselector.cpp.i
.PHONY : src/scenes/editor/colorselector/colorselector.cpp.i

src/scenes/editor/colorselector/colorselector.s: src/scenes/editor/colorselector/colorselector.cpp.s

.PHONY : src/scenes/editor/colorselector/colorselector.s

# target to generate assembly for a file
src/scenes/editor/colorselector/colorselector.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/colorselector/colorselector.cpp.s
.PHONY : src/scenes/editor/colorselector/colorselector.cpp.s

src/scenes/editor/configmanager.o: src/scenes/editor/configmanager.cpp.o

.PHONY : src/scenes/editor/configmanager.o

# target to build an object file
src/scenes/editor/configmanager.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/configmanager.cpp.o
.PHONY : src/scenes/editor/configmanager.cpp.o

src/scenes/editor/configmanager.i: src/scenes/editor/configmanager.cpp.i

.PHONY : src/scenes/editor/configmanager.i

# target to preprocess a source file
src/scenes/editor/configmanager.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/configmanager.cpp.i
.PHONY : src/scenes/editor/configmanager.cpp.i

src/scenes/editor/configmanager.s: src/scenes/editor/configmanager.cpp.s

.PHONY : src/scenes/editor/configmanager.s

# target to generate assembly for a file
src/scenes/editor/configmanager.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/configmanager.cpp.s
.PHONY : src/scenes/editor/configmanager.cpp.s

src/scenes/editor/drawer.o: src/scenes/editor/drawer.cpp.o

.PHONY : src/scenes/editor/drawer.o

# target to build an object file
src/scenes/editor/drawer.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/drawer.cpp.o
.PHONY : src/scenes/editor/drawer.cpp.o

src/scenes/editor/drawer.i: src/scenes/editor/drawer.cpp.i

.PHONY : src/scenes/editor/drawer.i

# target to preprocess a source file
src/scenes/editor/drawer.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/drawer.cpp.i
.PHONY : src/scenes/editor/drawer.cpp.i

src/scenes/editor/drawer.s: src/scenes/editor/drawer.cpp.s

.PHONY : src/scenes/editor/drawer.s

# target to generate assembly for a file
src/scenes/editor/drawer.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/drawer.cpp.s
.PHONY : src/scenes/editor/drawer.cpp.s

src/scenes/editor/editor.o: src/scenes/editor/editor.cpp.o

.PHONY : src/scenes/editor/editor.o

# target to build an object file
src/scenes/editor/editor.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/editor.cpp.o
.PHONY : src/scenes/editor/editor.cpp.o

src/scenes/editor/editor.i: src/scenes/editor/editor.cpp.i

.PHONY : src/scenes/editor/editor.i

# target to preprocess a source file
src/scenes/editor/editor.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/editor.cpp.i
.PHONY : src/scenes/editor/editor.cpp.i

src/scenes/editor/editor.s: src/scenes/editor/editor.cpp.s

.PHONY : src/scenes/editor/editor.s

# target to generate assembly for a file
src/scenes/editor/editor.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/editor.cpp.s
.PHONY : src/scenes/editor/editor.cpp.s

src/scenes/editor/frame.o: src/scenes/editor/frame.cpp.o

.PHONY : src/scenes/editor/frame.o

# target to build an object file
src/scenes/editor/frame.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/frame.cpp.o
.PHONY : src/scenes/editor/frame.cpp.o

src/scenes/editor/frame.i: src/scenes/editor/frame.cpp.i

.PHONY : src/scenes/editor/frame.i

# target to preprocess a source file
src/scenes/editor/frame.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/frame.cpp.i
.PHONY : src/scenes/editor/frame.cpp.i

src/scenes/editor/frame.s: src/scenes/editor/frame.cpp.s

.PHONY : src/scenes/editor/frame.s

# target to generate assembly for a file
src/scenes/editor/frame.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/frame.cpp.s
.PHONY : src/scenes/editor/frame.cpp.s

src/scenes/editor/framemanager.o: src/scenes/editor/framemanager.cpp.o

.PHONY : src/scenes/editor/framemanager.o

# target to build an object file
src/scenes/editor/framemanager.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/framemanager.cpp.o
.PHONY : src/scenes/editor/framemanager.cpp.o

src/scenes/editor/framemanager.i: src/scenes/editor/framemanager.cpp.i

.PHONY : src/scenes/editor/framemanager.i

# target to preprocess a source file
src/scenes/editor/framemanager.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/framemanager.cpp.i
.PHONY : src/scenes/editor/framemanager.cpp.i

src/scenes/editor/framemanager.s: src/scenes/editor/framemanager.cpp.s

.PHONY : src/scenes/editor/framemanager.s

# target to generate assembly for a file
src/scenes/editor/framemanager.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/framemanager.cpp.s
.PHONY : src/scenes/editor/framemanager.cpp.s

src/scenes/editor/frameselector/frameselector.o: src/scenes/editor/frameselector/frameselector.cpp.o

.PHONY : src/scenes/editor/frameselector/frameselector.o

# target to build an object file
src/scenes/editor/frameselector/frameselector.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/frameselector/frameselector.cpp.o
.PHONY : src/scenes/editor/frameselector/frameselector.cpp.o

src/scenes/editor/frameselector/frameselector.i: src/scenes/editor/frameselector/frameselector.cpp.i

.PHONY : src/scenes/editor/frameselector/frameselector.i

# target to preprocess a source file
src/scenes/editor/frameselector/frameselector.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/frameselector/frameselector.cpp.i
.PHONY : src/scenes/editor/frameselector/frameselector.cpp.i

src/scenes/editor/frameselector/frameselector.s: src/scenes/editor/frameselector/frameselector.cpp.s

.PHONY : src/scenes/editor/frameselector/frameselector.s

# target to generate assembly for a file
src/scenes/editor/frameselector/frameselector.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/frameselector/frameselector.cpp.s
.PHONY : src/scenes/editor/frameselector/frameselector.cpp.s

src/scenes/editor/gui/button.o: src/scenes/editor/gui/button.cpp.o

.PHONY : src/scenes/editor/gui/button.o

# target to build an object file
src/scenes/editor/gui/button.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/gui/button.cpp.o
.PHONY : src/scenes/editor/gui/button.cpp.o

src/scenes/editor/gui/button.i: src/scenes/editor/gui/button.cpp.i

.PHONY : src/scenes/editor/gui/button.i

# target to preprocess a source file
src/scenes/editor/gui/button.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/gui/button.cpp.i
.PHONY : src/scenes/editor/gui/button.cpp.i

src/scenes/editor/gui/button.s: src/scenes/editor/gui/button.cpp.s

.PHONY : src/scenes/editor/gui/button.s

# target to generate assembly for a file
src/scenes/editor/gui/button.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/gui/button.cpp.s
.PHONY : src/scenes/editor/gui/button.cpp.s

src/scenes/editor/gui/checkbox.o: src/scenes/editor/gui/checkbox.cpp.o

.PHONY : src/scenes/editor/gui/checkbox.o

# target to build an object file
src/scenes/editor/gui/checkbox.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/gui/checkbox.cpp.o
.PHONY : src/scenes/editor/gui/checkbox.cpp.o

src/scenes/editor/gui/checkbox.i: src/scenes/editor/gui/checkbox.cpp.i

.PHONY : src/scenes/editor/gui/checkbox.i

# target to preprocess a source file
src/scenes/editor/gui/checkbox.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/gui/checkbox.cpp.i
.PHONY : src/scenes/editor/gui/checkbox.cpp.i

src/scenes/editor/gui/checkbox.s: src/scenes/editor/gui/checkbox.cpp.s

.PHONY : src/scenes/editor/gui/checkbox.s

# target to generate assembly for a file
src/scenes/editor/gui/checkbox.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/gui/checkbox.cpp.s
.PHONY : src/scenes/editor/gui/checkbox.cpp.s

src/scenes/editor/gui/text.o: src/scenes/editor/gui/text.cpp.o

.PHONY : src/scenes/editor/gui/text.o

# target to build an object file
src/scenes/editor/gui/text.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/gui/text.cpp.o
.PHONY : src/scenes/editor/gui/text.cpp.o

src/scenes/editor/gui/text.i: src/scenes/editor/gui/text.cpp.i

.PHONY : src/scenes/editor/gui/text.i

# target to preprocess a source file
src/scenes/editor/gui/text.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/gui/text.cpp.i
.PHONY : src/scenes/editor/gui/text.cpp.i

src/scenes/editor/gui/text.s: src/scenes/editor/gui/text.cpp.s

.PHONY : src/scenes/editor/gui/text.s

# target to generate assembly for a file
src/scenes/editor/gui/text.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/gui/text.cpp.s
.PHONY : src/scenes/editor/gui/text.cpp.s

src/scenes/editor/gui/valuebox.o: src/scenes/editor/gui/valuebox.cpp.o

.PHONY : src/scenes/editor/gui/valuebox.o

# target to build an object file
src/scenes/editor/gui/valuebox.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/gui/valuebox.cpp.o
.PHONY : src/scenes/editor/gui/valuebox.cpp.o

src/scenes/editor/gui/valuebox.i: src/scenes/editor/gui/valuebox.cpp.i

.PHONY : src/scenes/editor/gui/valuebox.i

# target to preprocess a source file
src/scenes/editor/gui/valuebox.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/gui/valuebox.cpp.i
.PHONY : src/scenes/editor/gui/valuebox.cpp.i

src/scenes/editor/gui/valuebox.s: src/scenes/editor/gui/valuebox.cpp.s

.PHONY : src/scenes/editor/gui/valuebox.s

# target to generate assembly for a file
src/scenes/editor/gui/valuebox.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/gui/valuebox.cpp.s
.PHONY : src/scenes/editor/gui/valuebox.cpp.s

src/scenes/editor/history.o: src/scenes/editor/history.cpp.o

.PHONY : src/scenes/editor/history.o

# target to build an object file
src/scenes/editor/history.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/history.cpp.o
.PHONY : src/scenes/editor/history.cpp.o

src/scenes/editor/history.i: src/scenes/editor/history.cpp.i

.PHONY : src/scenes/editor/history.i

# target to preprocess a source file
src/scenes/editor/history.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/history.cpp.i
.PHONY : src/scenes/editor/history.cpp.i

src/scenes/editor/history.s: src/scenes/editor/history.cpp.s

.PHONY : src/scenes/editor/history.s

# target to generate assembly for a file
src/scenes/editor/history.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/history.cpp.s
.PHONY : src/scenes/editor/history.cpp.s

src/scenes/editor/languageManager.o: src/scenes/editor/languageManager.cpp.o

.PHONY : src/scenes/editor/languageManager.o

# target to build an object file
src/scenes/editor/languageManager.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/languageManager.cpp.o
.PHONY : src/scenes/editor/languageManager.cpp.o

src/scenes/editor/languageManager.i: src/scenes/editor/languageManager.cpp.i

.PHONY : src/scenes/editor/languageManager.i

# target to preprocess a source file
src/scenes/editor/languageManager.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/languageManager.cpp.i
.PHONY : src/scenes/editor/languageManager.cpp.i

src/scenes/editor/languageManager.s: src/scenes/editor/languageManager.cpp.s

.PHONY : src/scenes/editor/languageManager.s

# target to generate assembly for a file
src/scenes/editor/languageManager.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/languageManager.cpp.s
.PHONY : src/scenes/editor/languageManager.cpp.s

src/scenes/editor/menu/menu.o: src/scenes/editor/menu/menu.cpp.o

.PHONY : src/scenes/editor/menu/menu.o

# target to build an object file
src/scenes/editor/menu/menu.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/menu/menu.cpp.o
.PHONY : src/scenes/editor/menu/menu.cpp.o

src/scenes/editor/menu/menu.i: src/scenes/editor/menu/menu.cpp.i

.PHONY : src/scenes/editor/menu/menu.i

# target to preprocess a source file
src/scenes/editor/menu/menu.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/menu/menu.cpp.i
.PHONY : src/scenes/editor/menu/menu.cpp.i

src/scenes/editor/menu/menu.s: src/scenes/editor/menu/menu.cpp.s

.PHONY : src/scenes/editor/menu/menu.s

# target to generate assembly for a file
src/scenes/editor/menu/menu.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/menu/menu.cpp.s
.PHONY : src/scenes/editor/menu/menu.cpp.s

src/scenes/editor/menu/menubutton.o: src/scenes/editor/menu/menubutton.cpp.o

.PHONY : src/scenes/editor/menu/menubutton.o

# target to build an object file
src/scenes/editor/menu/menubutton.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/menu/menubutton.cpp.o
.PHONY : src/scenes/editor/menu/menubutton.cpp.o

src/scenes/editor/menu/menubutton.i: src/scenes/editor/menu/menubutton.cpp.i

.PHONY : src/scenes/editor/menu/menubutton.i

# target to preprocess a source file
src/scenes/editor/menu/menubutton.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/menu/menubutton.cpp.i
.PHONY : src/scenes/editor/menu/menubutton.cpp.i

src/scenes/editor/menu/menubutton.s: src/scenes/editor/menu/menubutton.cpp.s

.PHONY : src/scenes/editor/menu/menubutton.s

# target to generate assembly for a file
src/scenes/editor/menu/menubutton.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/menu/menubutton.cpp.s
.PHONY : src/scenes/editor/menu/menubutton.cpp.s

src/scenes/editor/menu/tinyfiledialogs.o: src/scenes/editor/menu/tinyfiledialogs.c.o

.PHONY : src/scenes/editor/menu/tinyfiledialogs.o

# target to build an object file
src/scenes/editor/menu/tinyfiledialogs.c.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/menu/tinyfiledialogs.c.o
.PHONY : src/scenes/editor/menu/tinyfiledialogs.c.o

src/scenes/editor/menu/tinyfiledialogs.i: src/scenes/editor/menu/tinyfiledialogs.c.i

.PHONY : src/scenes/editor/menu/tinyfiledialogs.i

# target to preprocess a source file
src/scenes/editor/menu/tinyfiledialogs.c.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/menu/tinyfiledialogs.c.i
.PHONY : src/scenes/editor/menu/tinyfiledialogs.c.i

src/scenes/editor/menu/tinyfiledialogs.s: src/scenes/editor/menu/tinyfiledialogs.c.s

.PHONY : src/scenes/editor/menu/tinyfiledialogs.s

# target to generate assembly for a file
src/scenes/editor/menu/tinyfiledialogs.c.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/menu/tinyfiledialogs.c.s
.PHONY : src/scenes/editor/menu/tinyfiledialogs.c.s

src/scenes/editor/thememanager.o: src/scenes/editor/thememanager.cpp.o

.PHONY : src/scenes/editor/thememanager.o

# target to build an object file
src/scenes/editor/thememanager.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/thememanager.cpp.o
.PHONY : src/scenes/editor/thememanager.cpp.o

src/scenes/editor/thememanager.i: src/scenes/editor/thememanager.cpp.i

.PHONY : src/scenes/editor/thememanager.i

# target to preprocess a source file
src/scenes/editor/thememanager.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/thememanager.cpp.i
.PHONY : src/scenes/editor/thememanager.cpp.i

src/scenes/editor/thememanager.s: src/scenes/editor/thememanager.cpp.s

.PHONY : src/scenes/editor/thememanager.s

# target to generate assembly for a file
src/scenes/editor/thememanager.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/thememanager.cpp.s
.PHONY : src/scenes/editor/thememanager.cpp.s

src/scenes/editor/toolbox/tool/floodfill.o: src/scenes/editor/toolbox/tool/floodfill.cpp.o

.PHONY : src/scenes/editor/toolbox/tool/floodfill.o

# target to build an object file
src/scenes/editor/toolbox/tool/floodfill.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/floodfill.cpp.o
.PHONY : src/scenes/editor/toolbox/tool/floodfill.cpp.o

src/scenes/editor/toolbox/tool/floodfill.i: src/scenes/editor/toolbox/tool/floodfill.cpp.i

.PHONY : src/scenes/editor/toolbox/tool/floodfill.i

# target to preprocess a source file
src/scenes/editor/toolbox/tool/floodfill.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/floodfill.cpp.i
.PHONY : src/scenes/editor/toolbox/tool/floodfill.cpp.i

src/scenes/editor/toolbox/tool/floodfill.s: src/scenes/editor/toolbox/tool/floodfill.cpp.s

.PHONY : src/scenes/editor/toolbox/tool/floodfill.s

# target to generate assembly for a file
src/scenes/editor/toolbox/tool/floodfill.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/floodfill.cpp.s
.PHONY : src/scenes/editor/toolbox/tool/floodfill.cpp.s

src/scenes/editor/toolbox/tool/line.o: src/scenes/editor/toolbox/tool/line.cpp.o

.PHONY : src/scenes/editor/toolbox/tool/line.o

# target to build an object file
src/scenes/editor/toolbox/tool/line.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/line.cpp.o
.PHONY : src/scenes/editor/toolbox/tool/line.cpp.o

src/scenes/editor/toolbox/tool/line.i: src/scenes/editor/toolbox/tool/line.cpp.i

.PHONY : src/scenes/editor/toolbox/tool/line.i

# target to preprocess a source file
src/scenes/editor/toolbox/tool/line.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/line.cpp.i
.PHONY : src/scenes/editor/toolbox/tool/line.cpp.i

src/scenes/editor/toolbox/tool/line.s: src/scenes/editor/toolbox/tool/line.cpp.s

.PHONY : src/scenes/editor/toolbox/tool/line.s

# target to generate assembly for a file
src/scenes/editor/toolbox/tool/line.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/line.cpp.s
.PHONY : src/scenes/editor/toolbox/tool/line.cpp.s

src/scenes/editor/toolbox/tool/pencil.o: src/scenes/editor/toolbox/tool/pencil.cpp.o

.PHONY : src/scenes/editor/toolbox/tool/pencil.o

# target to build an object file
src/scenes/editor/toolbox/tool/pencil.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/pencil.cpp.o
.PHONY : src/scenes/editor/toolbox/tool/pencil.cpp.o

src/scenes/editor/toolbox/tool/pencil.i: src/scenes/editor/toolbox/tool/pencil.cpp.i

.PHONY : src/scenes/editor/toolbox/tool/pencil.i

# target to preprocess a source file
src/scenes/editor/toolbox/tool/pencil.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/pencil.cpp.i
.PHONY : src/scenes/editor/toolbox/tool/pencil.cpp.i

src/scenes/editor/toolbox/tool/pencil.s: src/scenes/editor/toolbox/tool/pencil.cpp.s

.PHONY : src/scenes/editor/toolbox/tool/pencil.s

# target to generate assembly for a file
src/scenes/editor/toolbox/tool/pencil.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/pencil.cpp.s
.PHONY : src/scenes/editor/toolbox/tool/pencil.cpp.s

src/scenes/editor/toolbox/tool/pipette.o: src/scenes/editor/toolbox/tool/pipette.cpp.o

.PHONY : src/scenes/editor/toolbox/tool/pipette.o

# target to build an object file
src/scenes/editor/toolbox/tool/pipette.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/pipette.cpp.o
.PHONY : src/scenes/editor/toolbox/tool/pipette.cpp.o

src/scenes/editor/toolbox/tool/pipette.i: src/scenes/editor/toolbox/tool/pipette.cpp.i

.PHONY : src/scenes/editor/toolbox/tool/pipette.i

# target to preprocess a source file
src/scenes/editor/toolbox/tool/pipette.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/pipette.cpp.i
.PHONY : src/scenes/editor/toolbox/tool/pipette.cpp.i

src/scenes/editor/toolbox/tool/pipette.s: src/scenes/editor/toolbox/tool/pipette.cpp.s

.PHONY : src/scenes/editor/toolbox/tool/pipette.s

# target to generate assembly for a file
src/scenes/editor/toolbox/tool/pipette.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/pipette.cpp.s
.PHONY : src/scenes/editor/toolbox/tool/pipette.cpp.s

src/scenes/editor/toolbox/tool/spray.o: src/scenes/editor/toolbox/tool/spray.cpp.o

.PHONY : src/scenes/editor/toolbox/tool/spray.o

# target to build an object file
src/scenes/editor/toolbox/tool/spray.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/spray.cpp.o
.PHONY : src/scenes/editor/toolbox/tool/spray.cpp.o

src/scenes/editor/toolbox/tool/spray.i: src/scenes/editor/toolbox/tool/spray.cpp.i

.PHONY : src/scenes/editor/toolbox/tool/spray.i

# target to preprocess a source file
src/scenes/editor/toolbox/tool/spray.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/spray.cpp.i
.PHONY : src/scenes/editor/toolbox/tool/spray.cpp.i

src/scenes/editor/toolbox/tool/spray.s: src/scenes/editor/toolbox/tool/spray.cpp.s

.PHONY : src/scenes/editor/toolbox/tool/spray.s

# target to generate assembly for a file
src/scenes/editor/toolbox/tool/spray.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/spray.cpp.s
.PHONY : src/scenes/editor/toolbox/tool/spray.cpp.s

src/scenes/editor/toolbox/tool/tool.o: src/scenes/editor/toolbox/tool/tool.cpp.o

.PHONY : src/scenes/editor/toolbox/tool/tool.o

# target to build an object file
src/scenes/editor/toolbox/tool/tool.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/tool.cpp.o
.PHONY : src/scenes/editor/toolbox/tool/tool.cpp.o

src/scenes/editor/toolbox/tool/tool.i: src/scenes/editor/toolbox/tool/tool.cpp.i

.PHONY : src/scenes/editor/toolbox/tool/tool.i

# target to preprocess a source file
src/scenes/editor/toolbox/tool/tool.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/tool.cpp.i
.PHONY : src/scenes/editor/toolbox/tool/tool.cpp.i

src/scenes/editor/toolbox/tool/tool.s: src/scenes/editor/toolbox/tool/tool.cpp.s

.PHONY : src/scenes/editor/toolbox/tool/tool.s

# target to generate assembly for a file
src/scenes/editor/toolbox/tool/tool.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/tool/tool.cpp.s
.PHONY : src/scenes/editor/toolbox/tool/tool.cpp.s

src/scenes/editor/toolbox/toolbox.o: src/scenes/editor/toolbox/toolbox.cpp.o

.PHONY : src/scenes/editor/toolbox/toolbox.o

# target to build an object file
src/scenes/editor/toolbox/toolbox.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/toolbox.cpp.o
.PHONY : src/scenes/editor/toolbox/toolbox.cpp.o

src/scenes/editor/toolbox/toolbox.i: src/scenes/editor/toolbox/toolbox.cpp.i

.PHONY : src/scenes/editor/toolbox/toolbox.i

# target to preprocess a source file
src/scenes/editor/toolbox/toolbox.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/toolbox.cpp.i
.PHONY : src/scenes/editor/toolbox/toolbox.cpp.i

src/scenes/editor/toolbox/toolbox.s: src/scenes/editor/toolbox/toolbox.cpp.s

.PHONY : src/scenes/editor/toolbox/toolbox.s

# target to generate assembly for a file
src/scenes/editor/toolbox/toolbox.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/scenes/editor/toolbox/toolbox.cpp.s
.PHONY : src/scenes/editor/toolbox/toolbox.cpp.s

src/shaderload.o: src/shaderload.cpp.o

.PHONY : src/shaderload.o

# target to build an object file
src/shaderload.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/shaderload.cpp.o
.PHONY : src/shaderload.cpp.o

src/shaderload.i: src/shaderload.cpp.i

.PHONY : src/shaderload.i

# target to preprocess a source file
src/shaderload.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/shaderload.cpp.i
.PHONY : src/shaderload.cpp.i

src/shaderload.s: src/shaderload.cpp.s

.PHONY : src/shaderload.s

# target to generate assembly for a file
src/shaderload.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/shaderload.cpp.s
.PHONY : src/shaderload.cpp.s

src/shadermanager.o: src/shadermanager.cpp.o

.PHONY : src/shadermanager.o

# target to build an object file
src/shadermanager.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/shadermanager.cpp.o
.PHONY : src/shadermanager.cpp.o

src/shadermanager.i: src/shadermanager.cpp.i

.PHONY : src/shadermanager.i

# target to preprocess a source file
src/shadermanager.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/shadermanager.cpp.i
.PHONY : src/shadermanager.cpp.i

src/shadermanager.s: src/shadermanager.cpp.s

.PHONY : src/shadermanager.s

# target to generate assembly for a file
src/shadermanager.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/shadermanager.cpp.s
.PHONY : src/shadermanager.cpp.s

src/texload.o: src/texload.cpp.o

.PHONY : src/texload.o

# target to build an object file
src/texload.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/texload.cpp.o
.PHONY : src/texload.cpp.o

src/texload.i: src/texload.cpp.i

.PHONY : src/texload.i

# target to preprocess a source file
src/texload.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/texload.cpp.i
.PHONY : src/texload.cpp.i

src/texload.s: src/texload.cpp.s

.PHONY : src/texload.s

# target to generate assembly for a file
src/texload.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/texload.cpp.s
.PHONY : src/texload.cpp.s

src/texturemanager.o: src/texturemanager.cpp.o

.PHONY : src/texturemanager.o

# target to build an object file
src/texturemanager.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/texturemanager.cpp.o
.PHONY : src/texturemanager.cpp.o

src/texturemanager.i: src/texturemanager.cpp.i

.PHONY : src/texturemanager.i

# target to preprocess a source file
src/texturemanager.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/texturemanager.cpp.i
.PHONY : src/texturemanager.cpp.i

src/texturemanager.s: src/texturemanager.cpp.s

.PHONY : src/texturemanager.s

# target to generate assembly for a file
src/texturemanager.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/texturemanager.cpp.s
.PHONY : src/texturemanager.cpp.s

src/timestep.o: src/timestep.cpp.o

.PHONY : src/timestep.o

# target to build an object file
src/timestep.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/timestep.cpp.o
.PHONY : src/timestep.cpp.o

src/timestep.i: src/timestep.cpp.i

.PHONY : src/timestep.i

# target to preprocess a source file
src/timestep.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/timestep.cpp.i
.PHONY : src/timestep.cpp.i

src/timestep.s: src/timestep.cpp.s

.PHONY : src/timestep.s

# target to generate assembly for a file
src/timestep.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/timestep.cpp.s
.PHONY : src/timestep.cpp.s

src/transform.o: src/transform.cpp.o

.PHONY : src/transform.o

# target to build an object file
src/transform.cpp.o:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/transform.cpp.o
.PHONY : src/transform.cpp.o

src/transform.i: src/transform.cpp.i

.PHONY : src/transform.i

# target to preprocess a source file
src/transform.cpp.i:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/transform.cpp.i
.PHONY : src/transform.cpp.i

src/transform.s: src/transform.cpp.s

.PHONY : src/transform.s

# target to generate assembly for a file
src/transform.cpp.s:
	$(MAKE) -f CMakeFiles/MPS.dir/build.make CMakeFiles/MPS.dir/src/transform.cpp.s
.PHONY : src/transform.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... MPS"
	@echo "... edit_cache"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/app_run.o"
	@echo "... src/app_run.i"
	@echo "... src/app_run.s"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/framebuffermanager.o"
	@echo "... src/framebuffermanager.i"
	@echo "... src/framebuffermanager.s"
	@echo "... src/lib/SDL2_rotozoom.o"
	@echo "... src/lib/SDL2_rotozoom.i"
	@echo "... src/lib/SDL2_rotozoom.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/modules/module.o"
	@echo "... src/modules/module.i"
	@echo "... src/modules/module.s"
	@echo "... src/musicload.o"
	@echo "... src/musicload.i"
	@echo "... src/musicload.s"
	@echo "... src/pixel.o"
	@echo "... src/pixel.i"
	@echo "... src/pixel.s"
	@echo "... src/render/buffer.o"
	@echo "... src/render/buffer.i"
	@echo "... src/render/buffer.s"
	@echo "... src/render/func.o"
	@echo "... src/render/func.i"
	@echo "... src/render/func.s"
	@echo "... src/scenes/editor/colorselector/colorselector.o"
	@echo "... src/scenes/editor/colorselector/colorselector.i"
	@echo "... src/scenes/editor/colorselector/colorselector.s"
	@echo "... src/scenes/editor/configmanager.o"
	@echo "... src/scenes/editor/configmanager.i"
	@echo "... src/scenes/editor/configmanager.s"
	@echo "... src/scenes/editor/drawer.o"
	@echo "... src/scenes/editor/drawer.i"
	@echo "... src/scenes/editor/drawer.s"
	@echo "... src/scenes/editor/editor.o"
	@echo "... src/scenes/editor/editor.i"
	@echo "... src/scenes/editor/editor.s"
	@echo "... src/scenes/editor/frame.o"
	@echo "... src/scenes/editor/frame.i"
	@echo "... src/scenes/editor/frame.s"
	@echo "... src/scenes/editor/framemanager.o"
	@echo "... src/scenes/editor/framemanager.i"
	@echo "... src/scenes/editor/framemanager.s"
	@echo "... src/scenes/editor/frameselector/frameselector.o"
	@echo "... src/scenes/editor/frameselector/frameselector.i"
	@echo "... src/scenes/editor/frameselector/frameselector.s"
	@echo "... src/scenes/editor/gui/button.o"
	@echo "... src/scenes/editor/gui/button.i"
	@echo "... src/scenes/editor/gui/button.s"
	@echo "... src/scenes/editor/gui/checkbox.o"
	@echo "... src/scenes/editor/gui/checkbox.i"
	@echo "... src/scenes/editor/gui/checkbox.s"
	@echo "... src/scenes/editor/gui/text.o"
	@echo "... src/scenes/editor/gui/text.i"
	@echo "... src/scenes/editor/gui/text.s"
	@echo "... src/scenes/editor/gui/valuebox.o"
	@echo "... src/scenes/editor/gui/valuebox.i"
	@echo "... src/scenes/editor/gui/valuebox.s"
	@echo "... src/scenes/editor/history.o"
	@echo "... src/scenes/editor/history.i"
	@echo "... src/scenes/editor/history.s"
	@echo "... src/scenes/editor/languageManager.o"
	@echo "... src/scenes/editor/languageManager.i"
	@echo "... src/scenes/editor/languageManager.s"
	@echo "... src/scenes/editor/menu/menu.o"
	@echo "... src/scenes/editor/menu/menu.i"
	@echo "... src/scenes/editor/menu/menu.s"
	@echo "... src/scenes/editor/menu/menubutton.o"
	@echo "... src/scenes/editor/menu/menubutton.i"
	@echo "... src/scenes/editor/menu/menubutton.s"
	@echo "... src/scenes/editor/menu/tinyfiledialogs.o"
	@echo "... src/scenes/editor/menu/tinyfiledialogs.i"
	@echo "... src/scenes/editor/menu/tinyfiledialogs.s"
	@echo "... src/scenes/editor/thememanager.o"
	@echo "... src/scenes/editor/thememanager.i"
	@echo "... src/scenes/editor/thememanager.s"
	@echo "... src/scenes/editor/toolbox/tool/floodfill.o"
	@echo "... src/scenes/editor/toolbox/tool/floodfill.i"
	@echo "... src/scenes/editor/toolbox/tool/floodfill.s"
	@echo "... src/scenes/editor/toolbox/tool/line.o"
	@echo "... src/scenes/editor/toolbox/tool/line.i"
	@echo "... src/scenes/editor/toolbox/tool/line.s"
	@echo "... src/scenes/editor/toolbox/tool/pencil.o"
	@echo "... src/scenes/editor/toolbox/tool/pencil.i"
	@echo "... src/scenes/editor/toolbox/tool/pencil.s"
	@echo "... src/scenes/editor/toolbox/tool/pipette.o"
	@echo "... src/scenes/editor/toolbox/tool/pipette.i"
	@echo "... src/scenes/editor/toolbox/tool/pipette.s"
	@echo "... src/scenes/editor/toolbox/tool/spray.o"
	@echo "... src/scenes/editor/toolbox/tool/spray.i"
	@echo "... src/scenes/editor/toolbox/tool/spray.s"
	@echo "... src/scenes/editor/toolbox/tool/tool.o"
	@echo "... src/scenes/editor/toolbox/tool/tool.i"
	@echo "... src/scenes/editor/toolbox/tool/tool.s"
	@echo "... src/scenes/editor/toolbox/toolbox.o"
	@echo "... src/scenes/editor/toolbox/toolbox.i"
	@echo "... src/scenes/editor/toolbox/toolbox.s"
	@echo "... src/shaderload.o"
	@echo "... src/shaderload.i"
	@echo "... src/shaderload.s"
	@echo "... src/shadermanager.o"
	@echo "... src/shadermanager.i"
	@echo "... src/shadermanager.s"
	@echo "... src/texload.o"
	@echo "... src/texload.i"
	@echo "... src/texload.s"
	@echo "... src/texturemanager.o"
	@echo "... src/texturemanager.i"
	@echo "... src/texturemanager.s"
	@echo "... src/timestep.o"
	@echo "... src/timestep.i"
	@echo "... src/timestep.s"
	@echo "... src/transform.o"
	@echo "... src/transform.i"
	@echo "... src/transform.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

